#!/usr/bin/env bash
#:  * `show` <formula> [<formula>...]:
#:     Show the syntax-highlighted Ruby source of the specified formulae

function brew () {
    "${HOMEBREW_PREFIX}/bin/brew" "$@"
}

pygmentize="$(which pygmentize)"

if [[ ! -x $pygmentize ]]; then
    echo "* ERROR: The “pygmentize” command was not found"
    echo "* ERROR: Try installing the Python “pygments” package"
    return 1
else
    for argument in "$@"; do
        brew cat "${argument}" | "${pygmentize}" -l ruby -O "style=paraiso-dark"
        echo ""
    done
fi
